#!/usr/bin/env bash
# This script installs the Nginx web server and configures the initial "Hello
# world" page.

# Update package lists
apt-get update

# Install nginx
apt-get install -y nginx

# Check if nginx is installed successfully
if [ $? -ne 0 ]; then
	echo "Failed to install nginx. Exiting."
	exit 1
fi

# Set nginx to listen on port 80
sed -i 's/\(listen\s*\)80/\180/' /etc/nginx/sites-available/default

# Restart nginx
service nginx restart

# Check if nginx is running
if ! pgrep -x "nginx" > /dev/null; then
	echo "Nginx failed to start. Exiting."
	exit 1
fi

echo "Hello World" > /var/www/html/index.html
