#!/usr/bin/env bash
# This script installs the Nginx web server and configures the initial "Hello
# world" page.

apt-get update -y
apt-get install nginx -y
sed -i 's/80 default_server/80/' /etc/nginx/sites-available/default
/etc/init.d/nginx reload
echo "Hello World!" > /usr/share/nginx/html/index.html
