#!/usr/bin/env bash
# Configure a ufw firewall to block all incoming traffic
# except for TCP 22, 80, and 443.

# Check the staus of ufw
sudo ufw staus

# Install ufw if it is not installed
sudo apt install ufw

# Setup the firewall
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow incoming traffic on ports 22, 80, and 443
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Enable ufw
sudo ufw enable

# Check status
sudo ufw status verbose
